### ISSUE TITLE
Settings Values

### ISSUE THREAD

**Issue by habeebmatrix** [hypnoJerk/from_twitter_to_telegram#3]
Hi,
Could you please tell what are the values expected in the below setting:

APP_KEY = 'XXXxxXXXXXxxXXXXxXxxxXxxXxXXxxXxXxXxXXXxX' 
APP_SECRET = 'xxxXXXXXxXxXxxxXXxXxXxxXXXXxxXxXXXxxXXxxXxxxxxX' 
OAUTH_TOKEN = 'XXxXXXXXxxXXxxXxXxxxXXXxXxxxXxXXXxxXxXxXxxXxxx'
OAUTH_TOKEN_SECRET = 'XXXxXXXxXxxXXXxXxxXxXXxXXXxXxXXXXxXxXXxXX'

Which are related to Twitter and which are related to Telegram?
Also how do I generate these values.

**Comment by zeroc00I** [comment]
These are optional args. You can leave it empty.
Token telegram is being called in settings.py file by telegram_token variable.
